[package]
name = "testpack"
version = "1.0.0"
description = "just testing"
repository = "https://github.com/sam-thetutor/mopspackage"
keywords = [ "testing" ]
license = "MIT"

[dependencies]
base = "0.10.1"